language: python
python:
  - "2.7"
  - "3.5"
script: 
    - source activate travis
    - nosetests --with-doctest
    - python -m peddy -h
    - pwd

install:
    - sudo apt-get update
    - unset PYTHONPATH
    - unset PYTHONHOME
    - unset PYTHONUSER
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda create -q -n travis python=$TRAVIS_PYTHON_VERSION scipy scikit-learn cython pandas numpy networkx nose
    - source activate travis
    - pip install -U networkx
    - conda install -c bioconda cyvcf2
    - pip install -r requirements.txt
    - python setup.py install
    - pwd
