language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
script: 
    - nosetests --with-doctest

install:
    - pip install cython
    - pip install -r requirements.txt
    - python setup.py install
