language: c
python:
  - "2.7"
    #- "3.3"
    #- "3.4"
    #- "3.5"
script: 
    - source activate travis
    - nosetests --with-doctest
    - python -m peddy -h

install:
    - sudo apt-get update
    - unset PYTHONPATH
    - unset PYTHONHOME
    - unset PYTHONUSER
    - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda create -q -n travis python=2 scipy scikit-learn cython pandas numpy networkx
    - source activate travis
    - pip install -U networkx
    - conda install -c bioconda cyvcf2
    - pip install -r requirements.txt
    - python setup.py install
